//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public string IdActive { get; set; }
        public Nullable<int> IdEvents { get; set; }
        public string NameActive { get; set; }
        public Nullable<int> NumberDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> Idmoderation { get; set; }
        public Nullable<int> IdUserJudge { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
